version: '3'
services:
  scraper:
    build:
      context: ./web-scrapper  # Ruta hacia la carpeta del scraper
      dockerfile: Dockerfile  # Asegúrate de tener un Dockerfile en esa carpeta
    ports:
      - "8082:8080"
    networks:
      - app_network

  traffic_generator:
    build:
      context: ./proyecto_traffic_generator  # Ruta hacia la carpeta del generador de tráfico
      dockerfile: Dockerfile  # Asegúrate de tener un Dockerfile en esa carpeta
    ports:
      - "9092:9090"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
