services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./DatosElastic:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-net
  kibana:
    container_name: kibana
    image: kibana:9.0.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch-net
  filtering:
    container_name: filtrado
    build:
      context: ./Filtering
      dockerfile: Dockerfile
    volumes:
      - ./resultado:/resultado
  processing:
    container_name: procesamiento
    build:
      context: ./Processing
      dockerfile: Dockerfile
    volumes:
      - ./resultado:/resultado
    networks:
      - elasticsearch-net
  insert_data:
    container_name: insert_data
    build:
      context: ./DataInsert
      dockerfile: Dockerfile
    depends_on:
      - processing
    networks:
      - elasticsearch-net
    volumes:
      - ./resultado:/resultado
networks:
  elasticsearch-net:
    driver: bridge